export const main = 'https://crowdfunding.sanberdev.com'
export const auth = 'https://crowdfunding.sanberdev.com/api/auth/login'
export const user = 'https://crowdfunding.sanberdev.com/api/profile/get-profile'
export const update = 'https://crowdfunding.sanberdev.com/api/profile/update-profile'
export const register = 'https://crowdfunding.sanberdev.com/api/auth/register'
export const verification = 'https://crowdfunding.sanberdev.com/api/auth/verification'
export const reOtp = 'https://crowdfunding.sanberdev.com/api/auth/regenerate-otp'
export const passwordUpdate = 'https://crowdfunding.sanberdev.com/api/auth/update-password'